config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get '/home', to: 'static_pages#home' 
  

  get '/about', to: 'static_pages#about'
  
  get '/help', to: 'static_pages#help'
  
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'

  root 'static_pages#home' #a new helper named root_path will be created to redirect to this route
  
  
   get 'static_pages/dummy'# when you put this error will be : no action clled dummy 
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def index 
    render html: "Hello world"
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def help
    
  end
  
  def contact
    
  end
  
  def dummy
    
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def grabtitle(page_name='')
       
       full_title="Rails App"
        if page_name==''
           full_title
        else
            page_name+" | "+full_title
        end
    end
    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title><%=grabtitle(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

<%= yield %>

<%= render "layouts/footer" %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<html>
    <head>
        
    </head>
    <body>
        
    </body>
</html>

app/views/static_pages/dummy.html.erb
<% provide(:title, "Dummy") %>

<h1> Dummy Page</h1>

app/views/static_pages/help.html.erb
<% provide(:title,"help")%>

<html>
    
    <head>
        
    </head>
    <body>
        <h1>Help page</h1>
    </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>

<% provide(:title,"")%>

<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("ninja.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title,"Signup") %>


<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>